#ifndef RAGDOLL_H_INCLUDED
#define RAGDOLL_H_INCLUDED

#include "DemoApplication.h"
#include "LinearMath/btAlignedObjectArray.h"
#include "btBulletDynamicsCommon.h"

enum ePedBones
{
	BONE_PELVIS1 = 1,
	BONE_PELVIS = 2,
	BONE_SPINE1 = 3,
	BONE_UPPERTORSO = 4,
	BONE_NECK = 5,
	BONE_HEAD2 = 6,
	BONE_HEAD1 = 7,
	BONE_HEAD = 8,
	BONE_RIGHTUPPERTORSO = 21,
	BONE_RIGHTSHOULDER = 22,
	BONE_RIGHTELBOW = 23,
	BONE_RIGHTWRIST = 24,
	BONE_RIGHTHAND = 25,
	BONE_RIGHTTHUMB = 26,
	BONE_LEFTUPPERTORSO = 31,
	BONE_LEFTSHOULDER = 32,
	BONE_LEFTELBOW = 33,
	BONE_LEFTWRIST = 34,
	BONE_LEFTHAND = 35,
	BONE_LEFTTHUMB = 36,
	BONE_LEFTHIP = 41,
	BONE_LEFTKNEE = 42,
	BONE_LEFTANKLE = 43,
	BONE_LEFTFOOT = 44,
	BONE_RIGHTHIP = 51,
	BONE_RIGHTKNEE = 52,
	BONE_RIGHTANKLE = 53,
	BONE_RIGHTFOOT = 54,
};




class RagDoll
{
	public:
	enum
	{
		BODYPART_PELVIS1 = BONE_PELVIS1,
		BODYPART_PELVIS = BONE_PELVIS,
		BODYPART_SPINE1 = BONE_SPINE1,
		BODYPART_UPPER_TORSO = BONE_UPPERTORSO,
		BODYPART_NECK = BONE_NECK,
		BODYPART_HEAD2 = BONE_HEAD2,
		BODYPART_HEAD1 = BONE_HEAD1,
		BODYPART_HEAD = BONE_HEAD,
		BODYPART_RIGHT_UPPER_TORSO = BONE_RIGHTUPPERTORSO,
		BODYPART_RIGHT_SHOULDER = BONE_RIGHTSHOULDER,
		BODYPART_RIGHT_ELBOW = BONE_RIGHTELBOW,
		BODYPART_RIGHT_WRIST = BONE_RIGHTWRIST,
		BODYPART_RIGHT_HAND = BONE_RIGHTHAND,
		BODYPART_RIGHT_THUMB = BONE_RIGHTTHUMB,
		BODYPART_LEFT_UPPER_TORSO = BONE_LEFTUPPERTORSO,
		BODYPART_LEFT_SHOULDER = BONE_LEFTSHOULDER,
		BODYPART_LEFT_ELBOW = BONE_LEFTELBOW,
		BODYPART_LEFT_WRIST = BONE_LEFTWRIST,
		BODYPART_LEFT_HAND = BONE_LEFTHAND,
		BODYPART_LEFT_THUMB = BONE_LEFTTHUMB,
		BODYPART_LEFT_HIP = BONE_LEFTHIP,
		BODYPART_LEFT_KNEE = BONE_LEFTKNEE,
		BODYPART_LEFT_ANKLE = BONE_LEFTANKLE,
		BODYPART_LEFT_FOOT = BONE_LEFTFOOT,
		BODYPART_RIGHT_HIP = BONE_RIGHTHIP,
		BODYPART_RIGHT_KNEE = BONE_RIGHTKNEE,
		BODYPART_RIGHT_ANKLE = BONE_RIGHTANKLE,
		BODYPART_RIGHT_FOOT = BONE_RIGHTFOOT,

		BODYPART_SPINE = BODYPART_UPPER_TORSO,
		BODYPART_LEFT_UPPER_LEG = BODYPART_LEFT_HIP,
		BODYPART_LEFT_LOWER_LEG = BODYPART_LEFT_KNEE,
		BODYPART_RIGHT_UPPER_LEG = BODYPART_RIGHT_HIP,
		BODYPART_RIGHT_LOWER_LEG = BODYPART_RIGHT_KNEE,
		BODYPART_LEFT_UPPER_ARM = BODYPART_LEFT_SHOULDER,
		BODYPART_LEFT_LOWER_ARM = BODYPART_LEFT_ELBOW,
		BODYPART_RIGHT_UPPER_ARM = BODYPART_RIGHT_SHOULDER,
		BODYPART_RIGHT_LOWER_ARM = BODYPART_RIGHT_ELBOW,

		BODYPART_COUNT = BONE_RIGHTFOOT + 1
	};

	enum
	{
		JOINT_PELVIS_TO_UPPERTORSO = 0,
		JOINT_UPPERTORSO_TO_NECK,
		JOINT_NECK_TO_HEAD,

		JOINT_PELVIS_TO_LEFTHIP,
		JOINT_LEFTHIP_TO_LEFTKNEE,
		JOINT_LEFTKNEE_TO_LEFTANKLE,
		JOINT_LEFTKNEE_TO_LEFTFOOT,
	
		JOINT_PELVIS_TO_RIGHTHIP,
		JOINT_RIGHTHIP_TO_RIGHTKNEE,
		JOINT_RIGHTKNEE_TO_RIGHTANKLE,
		JOINT_RIGHTKNEE_TO_RIGHTFOOT,

		JOINT_UPPERTORSO_TO_LEFTSHOULDER,
		JOINT_LEFTSHOULDER_TO_LEFTELBOW,

		JOINT_UPPERTORSO_TO_RIGHTSHOULDER,
		JOINT_RIGHTSHOULDER_TO_RIGHTELBOW,

		JOINT_RIGHTELBOW_TO_RIGHTWRIST,
		JOINT_RIGHTWRIST_TO_RIGHTHAND,
		
		JOINT_LEFTELBOW_TO_LEFTWRIST,
		JOINT_LEFTWRIST_TO_LEFTHAND,

		JOINT_COUNT
	};

	private:

	btDynamicsWorld* m_ownerWorld;
	btCollisionShape* m_shapes[BODYPART_COUNT];
	btRigidBody* m_bodies[BODYPART_COUNT];
	btTypedConstraint* m_joints[JOINT_COUNT];

	btRigidBody* localCreateRigidBody (btScalar mass, const btTransform& startTransform, btCollisionShape* shape);

public:
	RagDoll (btDynamicsWorld* ownerWorld,
				const btVector3& positionOffset,
				btScalar scale_ragdoll = btScalar(1.0));

	~RagDoll ();
};



#endif // RAGDOLL_H_INCLUDED
